# recommendation_config.yaml
# Configuration settings for the recommendation system

version: 1.0
appName: "E-Commerce Recommendation Engine"
environment: "production"

# Database connection settings
database:
  type: "mysql"
  host: "${DB_HOST}"
  port: 3306
  name: "ecommerce_recommendations"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  connectionPool:
    minConnections: 5
    maxConnections: 20
    idleTimeout: 300
  queryTimeout: 5000  # ms

# Redis cache settings
redis:
  host: "${REDIS_HOST}"
  port: 6379
  password: "${REDIS_PASSWORD}"
  db: 0
  connectionTimeout: 2000  # ms
  ttlDefaults:
    userRecommendations: 3600  # 1 hour
    popularProducts: 86400  # 24 hours
    similarProducts: 604800  # 7 days

# API settings
api:
  port: 8080
  basePath: "/api/v1"
  rateLimit:
    maxRequests: 100
    windowMs: 60000  # 1 minute
  timeout: 30000  # 30 seconds
  cors:
    enabled: true
    origins:
      - "https://example.com"
      - "https://www.example.com"
    methods:
      - "GET"
      - "POST"

# Recommendation algorithm settings
recommendations:
  defaultLimit: 10
  algorithms:
    collaborative:
      enabled: true
      weight: 0.7
      minInteractions: 5
      similarityMetric: "cosine"
      neighborhoodSize: 50
    contentBased:
      enabled: true
      weight: 0.3
      features:
        - name: "category"
          weight: 0.4
        - name: "brand"
          weight: 0.2
        - name: "price"
          weight: 0.2
        - name: "attributes"
          weight: 0.2
    hybrid:
      enabled: true
      strategy: "weighted"
      fallbackOrder:
        - "collaborative"
        - "contentBased"
        - "popular"
    popular:
      enabled: true
      timeWindow: 604800  # 7 days
      boostNewProducts: true
      newProductDays: 30
  
  # User segmentation for personalization
  userSegments:
    enabled: true
    updateFrequency: 86400  # 24 hours
    segments:
      - name: "new_users"
        definition: "registration_date >= NOW() - INTERVAL 30 DAY"
        algorithm: "popular"
      - name: "power_users"
        definition: "purchase_count > 5 AND last_purchase_date >= NOW() - INTERVAL 90 DAY"
        algorithm: "collaborative"
      - name: "dormant_users"
        definition: "last_activity_date < NOW() - INTERVAL 60 DAY"
        algorithm: "trending"

# Model settings
models:
  basePath: "/opt/recommendation-system/models"
  trainingSchedule: "0 2 * * *"  # 2 AM daily in cron format
  embedding:
    dimensions: 100
    optimizer: "adam"
    learningRate: 0.001
    batchSize: 128
    epochs: 20
  evaluation:
    testSize: 0.2
    metrics:
      - "precision@5"
      - "recall@10"
      - "ndcg@10"
      - "map@10"

# Monitoring and logging
monitoring:
  enabled: true
  metrics:
    - name: "recommendation_generation_time"
      type: "histogram"
    - name: "cache_hit_ratio"
      type: "gauge"
    - name: "recommendation_click_rate"
      type: "counter"
  alerting:
    errorThreshold: 0.05  # Alert if error rate exceeds 5%
    responseTimeThreshold: 500  # ms
    recipients:
      - "engineering@example.com"
      - "product@example.com"
  logging:
    level: "${LOG_LEVEL:-info}"
    format: "json"
    destination: "stdout"
    errorLog: "/var/log/recommendation-engine/error.log"

# A/B testing configuration
experiments:
  enabled: true
  defaultDuration: 604800  # 7 days
  minSampleSize: 1000
  significanceLevel: 0.05
  metrics:
    primary: "conversion_rate"
    secondary:
      - "click_through_rate"
      - "average_order_value"